#!/bin/sh

# Install Thunderbird binaries

# Extracts into the 'thunderbird' folder
tar xjf thunderbird.tar.bz2
rm thunderbird.tar.bz2

THUNDERBIRD_DIR=$(pwd)/thunderbird

# Install languages

# Retrieve the extension id for an addon from its install.rdf
# This function is taken from http://kb.mozillazine.org/Determine_extension_ID
get_extension_id() {
  unzip -qc $1 install.rdf | xmlstarlet sel \
    -N rdf=http://www.w3.org/1999/02/22-rdf-syntax-ns# \
    -N em=http://www.mozilla.org/2004/em-rdf# \
    -t -v \
    "//rdf:Description[@about='urn:mozilla:install-manifest']/@em:id"
}

EXTENSIONS_DIR=${THUNDERBIRD_DIR}/distribution/extensions
mkdir -p ${EXTENSIONS_DIR}
for addon in $(ls *.xpi); do
    mv "${addon}" "${EXTENSIONS_DIR}/$(get_extension_id ${addon}).xpi"
done

# Override preferences
PREFERENCES_DIR=${THUNDERBIRD_DIR}/browser/defaults/preferences
mkdir -p ${PREFERENCES_DIR}
ln -s /app/cache/mozilla/endless-default-prefs.js ${PREFERENCES_DIR}
